/* eslint-disable no-console */
import fs from 'fs'
import path from 'path'

const iconsDir = path.resolve('src', 'shared', 'const', 'icons', 'assets')
const outputFile = path.resolve('src', 'shared', 'const', 'icons', 'index.ts')
const files = fs.readdirSync(iconsDir).filter((file) => file.endsWith('.svg'))

const imports = files.map((file) => {
    const name = path.basename(file, '.svg')

    return `import ${name} from './assets/${file}'`
})

const exportObject = `const ICONS = {
${files
    .map((file, index) => {
        const name = path.basename(file, '.svg')
        const isLast = index === files.length - 1
        const comma = isLast ? '' : ','

        return `    ${name}${comma}`
    })
    .join('\n')}
}

export type IconType = keyof typeof ICONS
export default ICONS
`

const headerComment = `/**
 * This file is auto-generated by the icons generation script.
 * Do not edit this file manually.
 *
 * Generated on: ${new Date().toLocaleString()}
 **/`

const content = `${headerComment}\n\n${imports.join('\n')}\n\n${exportObject}`

fs.writeFileSync(outputFile, content, 'utf8')

console.log('Icons generated successfully!')
